export const ACCEPT_ORDER_REQUEST = 'ACCEPT_ORDER_REQUEST';
export const ACCEPT_ORDER_SUCCESS = 'ACCEPT_ORDER_SUCCESS';
export const ACCEPT_ORDER_FAIL = 'ACCEPT_ORDER_FAIL';

export const ACCEPT_PAYMENT_REQUEST = 'ACCEPT_PAYMENT_REQUEST';
export const ACCEPT_PAYMENT_SUCCESS = 'ACCEPT_PAYMENT_SUCCESS';
export const ACCEPT_PAYMENT_FAIL = 'ACCEPT_PAYMENT_FAIL';