export const CHECKOUT = 'CHECKOUT';

export const CHECKOUT_LIST_REQUEST = 'CHECKOUT_LIST_REQUEST';
export const CHECKOUT_LIST_SUCCESS = 'CHECKOUT_LIST_SUCCESS';
export const CHECKOUT_LIST_FAIL = 'CHECKOUT_LIST_FAIL';

export const CHECKOUT_REQUEST = 'CHECKOUT_REQUEST';
export const CHECKOUT_SUCCESS = 'CHECKOUT_SUCCESS';
export const CHECKOUT_FAIL = 'CHECKOUT_FAIL';
export const CHECKOUT_RESET = 'CHECKOUT_RESET';