export const LIST_FOOD_REQUEST = "LIST_FOOD_REQUEST";
export const LIST_FOOD_SUCCESS = "LIST_FOOD_SUCCESS";
export const LIST_FOOD_FAIL = "LIST_FOOD_FAIL";

export const LIST_FOOD_BY_STALLS_ID_REQUEST = "LIST_FOOD_BY_STALLS_ID_REQUEST";
export const LIST_FOOD_BY_STALLS_ID_SUCCESS = "LIST_FOOD_BY_STALLS_ID_SUCCESS";
export const LIST_FOOD_BY_STALLS_ID_FAIL = "LIST_FOOD_BY_STALLS_ID_FAIL";

export const CREATE_FOOD_REQUEST = "CREATE_FOOD_REQUEST";
export const CREATE_FOOD_SUCCESS = "CREATE_FOOD_SUCCESS";
export const CREATE_FOOD_FAIL = "CREATE_FOOD_FAIL";

export const UPDATE_FOOD_REQUEST = "UPDATE_FOOD_REQUEST";
export const UPDATE_FOOD_SUCCESS = "UPDATE_FOOD_SUCCESS";
export const UPDATE_FOOD_FAIL = "UPDATE_FOOD_FAIL";

export const DELETE_FOOD_REQUEST = "DELETE_FOOD_REQUEST";
export const DELETE_FOOD_SUCCESS = "DELETE_FOOD_SUCCESS";
export const DELETE_FOOD_FAIL = "DELETE_FOOD_FAIL";


