export const LIST_ORDER_BY_STALLS_ID_REQUEST = 'LIST_ORDER_BY_STALLS_ID_REQUEST';
export const LIST_ORDER_BY_STALLS_ID_SUCCESS = 'LIST_ORDER_BY_STALLS_ID_SUCCESS';
export const LIST_ORDER_BY_STALLS_ID_FAIL = 'LIST_ORDER_BY_STALLS_ID_FAIL';
